import {useEffect} from 'react';
import {pillars,legacy,experiences,products} from './data/content';
const A='/assets/';
const Photo=({src,alt})=><img src={A+src} alt={alt} loading="lazy" onError={e=>e.currentTarget.classList.add('missing')}/>;
export default function App(){
useEffect(()=>{const fn=()=>document.querySelector('.nav')?.classList.toggle('scrolled',scrollY>40);addEventListener('scroll',fn);return()=>removeEventListener('scroll',fn)},[]);
return <><nav className="nav"><div className="wrap navin"><a className="brand" href="#"><span className="mark">W</span><span>WE RUN THESE STREETZ</span></a><div className="navlinks"><a href="#movement">4Ws</a><a href="#legacy">Run the Legacy</a><a href="#events">Experiences</a><a href="#collect">Collect</a></div><a className="btn primary" href="#join">Join WRTS</a></div></nav>
<header className="hero"><div className="heroPhoto"/><div className="wrap heroContent"><div className="eyebrow">Movement Culture · Community Intelligence</div><h1>RUN.<br/>LEARN.<br/>BUILD.</h1><p className="heroLead">WRTS is a community wellness and engagement company powered by movement culture. We create experiences that move bodies, connect people and turn participation into lasting community value.</p><div className="actions"><a className="btn primary" href="#events">Move With Us</a><a className="btn outline" href="#legacy">Run the Legacy</a></div></div><div className="heroStrip">{pillars.map((p,i)=><div key={p.name}><b>0{i+1}</b>{p.name}</div>)}</div></header>
<section><div className="wrap storyGrid"><div className="photoPanel"><Photo src="photos/wrts-community.jpg" alt="WRTS community in motion"/><div className="photoCaption">Movement is how we enter. Community is what we build.</div></div><div className="storyCopy"><div className="eyebrow">We Run These Streetz</div><h3>More than miles.</h3><p>WRTS uses movement as the front door to connection, learning and community participation. Running may start the conversation, but the platform is built around what happens when people move, learn and build together.</p><div className="quote">The street is not just the route. It is the community.</div></div></div></section>
<section id="movement" className="pillars"><div className="wrap"><div className="head"><div className="eyebrow">The 4Ws</div><h2>Four ways we build stronger communities.</h2></div><div className="pillarGrid">{pillars.map((p,i)=><article className="pillar" key={p.name}><Photo src={p.image} alt={p.name}/><div className="pillarContent"><small>0{i+1} · {p.action}</small><h3>{p.name}</h3><p>{p.copy}</p></div></article>)}</div></div></section>
<section id="legacy" className="legacy"><div className="wrap"><div className="head"><div className="eyebrow">Run the Legacy · 4Ws Legacy Series</div><h2>Four Pillars. Four Legacies. One Movement.</h2><p>History becomes an experience you can move through, learn from and carry forward.</p></div><div className="legacyGrid">{legacy.map(x=><article className="chapter" key={x.title}><Photo src={x.image} alt={x.title}/><div className="chapterCopy"><small>{x.pillar} · {x.place}</small><h3>{x.title}</h3><p>{x.copy} <strong>{x.action}</strong></p></div></article>)}</div></div></section>
<section id="events"><div className="wrap"><div className="head"><div className="eyebrow">WRTS Experiences</div><h2>Built to move people—and keep them connected.</h2></div><div className="eventsGrid">{experiences.map(x=><article className="event" key={x.title}><Photo src={x.image} alt={x.title}/><div className="eventCopy"><div className="eyebrow">{x.label}</div><h3>{x.title}</h3><p>{x.copy}</p></div></article>)}</div></div></section>
<section id="collect" className="collect"><div className="wrap"><div className="head"><div className="eyebrow">Collect the Legacy</div><h2>Wear the movement. Keep the story.</h2></div><div className="collectGrid">{products.map(x=><article className="product" key={x.title}><div className="productPhoto"><Photo src={x.image} alt={x.title}/></div><div className="productBody"><span className="tag">{x.tag}</span><h3>{x.title}</h3><p>{x.copy}</p></div></article>)}</div></div></section>
<section id="join" className="cta"><div className="wrap"><div className="eyebrow white">Join the Movement</div><h2>YOUR STREET.<br/>YOUR LEGACY.</h2><p>Get first access to WRTS experiences, Run the Legacy drops, challenges and community activations.</p><form className="form" onSubmit={e=>{e.preventDefault();document.querySelector('#msg').textContent="You’re on the list. Welcome to WRTS."}}><input type="email" required placeholder="Email address"/><button className="btn" type="submit">Join WRTS</button></form><p id="msg"/></div></section>
<footer><div className="wrap foot"><strong>WE RUN THESE STREETZ</strong><span>Wealth · Wellness · Wisdom · Work</span><span>Run. Learn. Build.</span></div></footer></>}