import {useEffect,useState} from 'react';
import {siteConfig,quarters,currentQuarter,challenges,partnerTypes,impactMetrics,passportSample,q4Product} from './data/content';
import EventOS from './EventOS';
const Photo=({src,alt})=><img src={'/assets/'+src} alt={alt} loading="lazy" onError={e=>e.currentTarget.classList.add('missing')}/>;
function HubSpotForm({source='homepage',interest='General',campaign='community'}){useEffect(()=>{window.wrtsHubSpotContext={source,interest,campaign};const src='https://js-na2.hsforms.net/forms/embed/247477120.js';let script=document.querySelector('script[data-wrts-hubspot]');if(!script){script=document.createElement('script');script.src=src;script.defer=true;script.dataset.wrtsHubspot='true';document.body.appendChild(script)}},[source,interest,campaign]);return <div className="hubspotWrap" data-wrts-source={source} data-wrts-interest={interest} data-wrts-campaign={campaign}><div className="hs-form-frame" data-region="na2" data-form-id="b177ab50-1dd0-44e9-bb3b-7112141d9605" data-portal-id="247477120"></div></div>}
function Nav(){return <nav className="nav"><div className="wrap navin"><a className="brand" href="#home"><img src="/assets/brand/wrts-wordmark.webp" alt="WRTS" className="wordmark"/><span className="brandText">WE RUN THESE STREETZ</span></a><div className="navlinks">{siteConfig.navigation.slice(1).map(x=><a key={x} href={'#'+x.toLowerCase().replaceAll(' ','-')}>{x}</a>)}<a className="eventosNavLink" href="#eventos">EventOS Beta</a></div><a className="btn primary" href="#join">Join WRTS</a></div></nav>}
function Quarter(){return <section className="quarter"><div className="wrap quarterGrid"><div><div className="eyebrow">Now Running</div><h2>{currentQuarter.quarter} — {currentQuarter.pillar}</h2><h3>{currentQuarter.theme}</h3><p>{currentQuarter.purpose}</p><div className="actions"><a className="btn primary" href="#join">Join This Quarter</a><a className="btn darkOutline" href="#the-4ws">Explore the 4Ws</a></div></div><div className="cycle">{quarters.map(q=><div className={q.quarter===currentQuarter.quarter?'cycleItem active':'cycleItem'} key={q.quarter}><b>{q.quarter}</b><span>{q.pillar}</span><small>{q.theme}</small></div>)}</div></div><p className="cycleLine">Four quarters. Four dimensions of community advancement. One stronger community.</p></section>}
function FourWs(){return <section id="the-4ws" className="pillars"><div className="wrap"><div className="head"><div className="eyebrow">The WRTS Operating System</div><h2>One year. Four dimensions of community advancement.</h2><p>The Four Ws work as one continuous annual journey—not separate business units.</p></div><div className="pillarGrid">{quarters.map(q=><article className="wcard" key={q.quarter}><span>{q.quarter} · {q.months}</span><h3>{q.pillar}</h3><strong>{q.theme}</strong><p>{q.purpose}</p><em>{q.question}</em></article>)}</div></div></section>}
function Challenges(){const [filter,setFilter]=useState('All');const list=filter==='All'?challenges:challenges.filter(x=>x.pillar===filter);return <section id="challenges"><div className="wrap"><div className="head"><div className="eyebrow">Challenges</div><h2>Participation becomes progress.</h2><p>WRTS challenges create reusable pathways for community action across Wellness, Wealth, Wisdom and Work.</p></div><div className="filters">{['All','Wellness','Wealth','Wisdom','Work'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="challengeGrid">{list.map(x=><article className="challenge" key={x.title}><span className="tag">{x.pillar} · {x.quarter}</span><h3>{x.title}</h3><p>{x.description}</p><small>{x.format} · {x.status}</small><button className="textBtn">{x.cta} →</button></article>)}</div></div></section>}
function Q4Product(){return <section id="q4-product" className="q4Product"><div className="wrap q4Grid"><div className="q4Visual"><div className="giftBox"><span className="ribbonV"/><span className="ribbonH"/><div className="giftMark">WRTS</div><small>HOLIDAY EDITION</small></div><div className="ornament">{q4Product.message}</div></div><div className="q4Copy"><div className="eyebrow">Featured Q4 Product · {q4Product.pillar}</div><h2>{q4Product.title}</h2><h3>{q4Product.subtitle}</h3><p>{q4Product.description}</p><div className="q4Meta"><span>{q4Product.distance}</span><span>{q4Product.season}</span><span>First Edition · 250</span></div><div className="q4Features">{q4Product.features.slice(0,4).map(x=><span key={x}>✓ {x}</span>)}</div><div className="priceRow">{q4Product.pricing.map(x=><div key={x.label}><small>{x.label}</small><b>{x.price}</b></div>)}</div><div className="actions"><a className="btn holidayBtn" href="#join">Get Holiday Updates</a><a className="btn holidayOutline" href="#challenges">Explore Challenges</a></div><p className="partnerNote">Holiday charity partner acknowledgment: The Gifted Crate. No contribution or proceeds claim is associated with this product.</p></div></div></section>}
function Passport(){return <section id="community" className="passport"><div className="wrap passportGrid"><div><div className="eyebrow">WRTS Community</div><h2>Your Journey. Your Community. Your Passport.</h2><p>The WRTS Passport is designed to become each participant's record of challenges, experiences, learning, service, badges and progress through the annual Four Ws cycle.</p><a className="btn primary" href="#passport-demo">Explore WRTS Passport</a></div><div className="passportCard" id="passport-demo"><div className="passportTop"><span>MY WRTS PASSPORT</span><b>2/4 PILLARS ACTIVATED</b></div>{passportSample.map(x=><div className="passportRow" key={x.pillar}><strong>{x.pillar}</strong><span>{x.status}</span></div>)}<small>Prototype data · persistent accounts planned</small></div></div></section>}
function Intelligence(){return <section className="intelligence"><div className="wrap"><div className="head"><div className="eyebrow">Community Intelligence</div><h2>Community Should Shape What Comes Next.</h2><p>WRTS learns from participation, feedback, partnerships and community activity without turning community engagement into surveillance.</p></div><div className="listen">{['Listen','Engage','Learn','Improve'].map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span></div>)}</div></div></section>}
function Impact(){return <section id="impact"><div className="wrap"><div className="head"><div className="eyebrow">Impact</div><h2>Measure what community progress makes possible.</h2><p>Verified production metrics will populate this layer as WRTS programs and integrations come online.</p></div><div className="metrics">{impactMetrics.map(x=><div key={x.label}><b>{x.value}</b><span>{x.label}</span><small>Awaiting verified data</small></div>)}</div></div></section>}
function Partners(){return <section id="partners" className="partners"><div className="wrap"><div className="head"><div className="eyebrow">Partners</div><h2>Build With the Community.</h2><p>Individuals participate. Organizations activate. Sponsors expand access. Partners scale impact.</p></div><div className="partnerGrid">{partnerTypes.map(x=><article key={x.title}><h3>{x.title}</h3><p>{x.copy}</p><a href="#join">Start a Conversation →</a></article>)}</div></div></section>}
function MarketingApp(){useEffect(()=>{const fn=()=>document.querySelector('.nav')?.classList.toggle('scrolled',scrollY>40);addEventListener('scroll',fn);return()=>removeEventListener('scroll',fn)},[]);return <><Nav/><header id="home" className="hero"><div className="heroPhoto"/><div className="wrap heroContent"><div className="eyebrow">Community + Movement + Culture + Progress</div><h1>MOVE FORWARD<br/><span>TOGETHER.</span></h1><p className="heroLead">WRTS strengthens communities through Wellness, Wealth, Wisdom, and Work—using challenges, shared experiences, education, and movement to turn participation into progress.</p><div className="actions"><a className="btn primary" href="#join">Join the Community</a><a className="btn outline" href="#the-4ws">Explore the 4Ws</a></div></div></header><Quarter/><FourWs/>
<section className="how"><div className="wrap"><div className="head"><div className="eyebrow">How WRTS Works</div><h2>Community is the protagonist.</h2></div><div className="steps">{['Connect','Participate','Progress','Give Back'].map((x,i)=><div key={x}><b>0{i+1}</b><h3>{x}</h3></div>)}</div></div></section>
<Challenges/><Q4Product/><Passport/><Intelligence/><Impact/><Partners/>
<section id="about" className="about"><div className="wrap storyGrid"><div><div className="eyebrow">About WRTS</div><h2>Movement is bigger than running.</h2><p>Physical movement, financial movement, intellectual growth, professional advancement, community participation and collective progress all belong here. Running remains part of the culture, but it is a mechanism for engagement—not the entire business.</p></div><div className="photoPanel"><Photo src="photos/wrts-community.jpg" alt="Neighbors participating in a WRTS community experience"/></div></div></section>
<section id="join" className="cta"><div className="wrap"><div className="eyebrow white">Stay in the Movement</div><h2>MOVE FORWARD TOGETHER.</h2><p>Join WRTS and choose the Four Ws that matter most to you. Your submission is captured directly in the WRTS HubSpot CRM.</p><HubSpotForm source="homepage" interest="4Ws Community" campaign="join-wrts"/></div></section>
<footer><div className="wrap foot"><div className="footerBrand"><img src="/assets/brand/wrts-primary-logo.webp" alt="We Run These Streetz lion logo"/><strong>WE RUN THESE STREETZ</strong></div><span>Wellness · Wealth · Wisdom · Work</span><span>Move Forward Together.</span></div></footer></>}

export default function App(){
  const route=window.location.hash.startsWith('#eventos')?'eventos':'marketing';
  const [appRoute,setAppRoute]=useState(route);
  useEffect(()=>{
    const onHash=()=>setAppRoute(window.location.hash.startsWith('#eventos')?'eventos':'marketing');
    window.addEventListener('hashchange',onHash);
    return()=>window.removeEventListener('hashchange',onHash);
  },[]);
  return appRoute==='eventos'?<EventOS/>:<MarketingApp/>;
}
